# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "tests"
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
 # Decode Google services configuration file
      - name: Decode google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > app/google-services.json
    
 # Check the code with Android Linter UNCHECK WHEN READY TO DEBUG THE PROJECT
 #     - name: Run Android Linter
 #       run: ./gradlew lintStagingDebug
 
      - name: Change wrapper permissions
        run: chmod +x ./gradlew 

      - name: Unit tests
        run: bash ./gradlew test --stacktrace
  instrumented-tests:
    name: Instrumented Tests
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # Decode Google services configuration file
      - name: Decode google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > app/google-services.json
      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          script: ./gradlew test createDebugAndroidTestCoverageReport 
      - name: Upload coverage reports
        run: bash <(curl -s https://codecov.io/bash)

