# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "documentation"
  documentation:
    name: Run dokka Documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Generate Dokka
        run: ./gradlew dokka
      
  # This workflow contains a single job called "tests"
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
 # Decode Google services configuration file
      - name: Decode google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > app/google-services.json
    
 # Check the code with Android linter
      - name: Run Android Linter
        run: ./gradlew lintStagingDebug
        
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
      
      - name: "Run UI Tests"
        uses: vgaidarji/android-github-actions-emulator@v1.0.1
