
name: Documentation

on:
  push:
    branches: master

jobs:
  dokka:
    name: Dokka
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Decode Google services configuration file
      - name: Decode google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > app/google-services.json

      - name: Merge changes
        run: |
          git config --local user.email "56782677+meadows115@users.noreply.github.com"
          git config --local user.name "Nikki Meadows"
          git merge --force origin/master

      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Run dokka
        run: |
          rm -rf dokka
          ./gradlew dokka
      - name: Commit files
        run: |
          git add -f docs
          git diff-index --quiet HEAD || git commit -m "Automatically update docs"
      - name: Push changes
        run: git push
